#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	/// <summary>
	/// Types of developer registration
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_registrationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allocation = 759150000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Credits = 759150001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AllocationandCredits = 759150002,
	}
}
#pragma warning restore CS1591
