#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_habitatconditionchoices
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Poor = 759150000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FairlyPoor = 759150001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Moderate = 759150002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FairlyGood = 759150003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Good = 759150004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConditionAssessmentNA = 759150005,
	}
}
#pragma warning restore CS1591
