#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	/// <summary>
	/// Strategic Significance of a Habitat
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_strategicsignificance
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Formallyidentifiedinlocalstrategy = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Locationecologicallydesirablebutnotinlocalstrategy = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Areacompensationnotinlocalstrategynolocalstrategy = 3,
	}
}
#pragma warning restore CS1591
