#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_amendmentsbpfstage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApplicantEligibility = 759150000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AmendmentEligibility = 759150001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GroundsforAmendment = 759150002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RemovalEligibility = 759150003,
	}
}
#pragma warning restore CS1591
