#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_amendmentsbpfstep
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DothechangesaffectBNGeligibilityofthesite_CompleteTasks = 759150000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Istheapplicantnamedashavingobligationsunderthelegalagreementtoundertakeormaintainworks = 759150001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Doestheapplicanthavetheconsentofarelevantperson = 759150002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Doestheapplicationcontainalltheinformationanddocumentationnecessary = 759150003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Isthesitetowhichtheapplicationrefersalreadyontheregister = 759150004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Isthegainsiteunallocated = 759150005,
	}
}
#pragma warning restore CS1591
