#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_journeytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Registration = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allocation = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Combined = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Amendment = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Removal = 5,
	}
}
#pragma warning restore CS1591
