#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_gainsiteregistration_bng_habitatenhancementworksenddatestatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EndDateProvided = 759150000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EndDateinPerpetuity = 759150001,
	}
	
	/// <summary>
	/// Status of the Gain Site
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_gainsiteregistration_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Gain Site
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_gainsiteregistration_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejected = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Registered = 759150001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Removed = 759150002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternallyRemoved = 759150003,
	}
	
	/// <summary>
	/// Holds Biodiversity Gain Site Details.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bng_gainsiteregistration")]
	public partial class bng_GainSiteRegistration : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bng_GainSiteRegistration() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bng_gainsiteregistration";
		
		public const string EntityLogicalCollectionName = "bng_gainsiteregistrations";
		
		public const string EntitySetName = "bng_gainsiteregistrations";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_amended")]
		public System.Nullable<bool> bng_Amended
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_amended");
			}
			set
			{
				this.SetAttributeValue("bng_amended", value);
			}
		}
		
		/// <summary>
		/// The Person who submitted the Biodiversity Net Gain Registration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_applicantcontactid")]
		public Microsoft.Xrm.Sdk.EntityReference bng_ApplicantContactID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_applicantcontactid");
			}
			set
			{
				this.SetAttributeValue("bng_applicantcontactid", value);
			}
		}
		
		/// <summary>
		/// The area in hectares of the Biodiversity Gain Site.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_areainhectares")]
		public System.Nullable<decimal> bng_AreaInHectares
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bng_areainhectares");
			}
			set
			{
				this.SetAttributeValue("bng_areainhectares", value);
			}
		}
		
		/// <summary>
		/// Holds Biodiversity Gain Site Registration Details.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_biodiversitygainsitenumber")]
		public string bng_BiodiversityGainSiteNumber
		{
			get
			{
				return this.GetAttributeValue<string>("bng_biodiversitygainsitenumber");
			}
			set
			{
				this.SetAttributeValue("bng_biodiversitygainsitenumber", value);
			}
		}
		
		/// <summary>
		/// The Biodiversity Value Declaration flag related to the Biodiversity Gain Site Registration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_biodiversityvaluedeclaration")]
		public System.Nullable<bool> bng_BiodiversityValueDeclaration
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_biodiversityvaluedeclaration");
			}
			set
			{
				this.SetAttributeValue("bng_biodiversityvaluedeclaration", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_casename")]
		public string bng_CaseName
		{
			get
			{
				return this.GetAttributeValue<string>("bng_casename");
			}
			set
			{
				this.SetAttributeValue("bng_casename", value);
			}
		}
		
		/// <summary>
		/// Case Type For Gain Site Registration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_casetype")]
		public virtual bng_casetype? bng_CaseType
		{
			get
			{
				return ((bng_casetype?)(EntityOptionSetEnum.GetEnum(this, "bng_casetype")));
			}
			set
			{
				this.SetAttributeValue("bng_casetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Easting of a Land Boundary Grid Reference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_easting")]
		public System.Nullable<int> bng_Easting
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bng_easting");
			}
			set
			{
				this.SetAttributeValue("bng_easting", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_enforcementbodycontact")]
		public Microsoft.Xrm.Sdk.EntityReference bng_EnforcementBodyContact
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_enforcementbodycontact");
			}
			set
			{
				this.SetAttributeValue("bng_enforcementbodycontact", value);
			}
		}
		
		/// <summary>
		/// The Funding Declaration flag related to the Biodiversity Gain Site Registration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_fundingdeclaration")]
		public System.Nullable<bool> bng_FundingDeclaration
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_fundingdeclaration");
			}
			set
			{
				this.SetAttributeValue("bng_fundingdeclaration", value);
			}
		}
		
		/// <summary>
		/// The portal Reference Number unique identifier.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_gainsitereference")]
		public string bng_GainSiteReference
		{
			get
			{
				return this.GetAttributeValue<string>("bng_gainsitereference");
			}
			set
			{
				this.SetAttributeValue("bng_gainsitereference", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_gainsiteregistrationid")]
		public System.Nullable<System.Guid> bng_GainSiteRegistrationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bng_gainsiteregistrationid");
			}
			set
			{
				this.SetAttributeValue("bng_gainsiteregistrationid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_gainsiteregistrationid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bng_GainSiteRegistrationId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_habitatenhancementworksenddate")]
		public System.Nullable<System.DateTime> bng_HabitatEnhancementWorksEndDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_habitatenhancementworksenddate");
			}
			set
			{
				this.SetAttributeValue("bng_habitatenhancementworksenddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_habitatenhancementworksenddatestatus")]
		public virtual bng_gainsiteregistration_bng_habitatenhancementworksenddatestatus? bng_HabitatEnhancementWorksEndDateStatus
		{
			get
			{
				return ((bng_gainsiteregistration_bng_habitatenhancementworksenddatestatus?)(EntityOptionSetEnum.GetEnum(this, "bng_habitatenhancementworksenddatestatus")));
			}
			set
			{
				this.SetAttributeValue("bng_habitatenhancementworksenddatestatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// The Start Date that relates to the Habitat Enhancement Works associated with the Biodiversity Gain Site.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_habitatenhancementworksstartdate")]
		public System.Nullable<System.DateTime> bng_HabitatEnhancementWorksStartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_habitatenhancementworksstartdate");
			}
			set
			{
				this.SetAttributeValue("bng_habitatenhancementworksstartdate", value);
			}
		}
		
		/// <summary>
		/// The Habitat Management & Monitoring Plan flag related to the Biodiversity Gain Site Registration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_habitatmanagementmonitoringplan")]
		public System.Nullable<bool> bng_HabitatManagementMonitoringPlan
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_habitatmanagementmonitoringplan");
			}
			set
			{
				this.SetAttributeValue("bng_habitatmanagementmonitoringplan", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_habitatplanincludedlegalagreementyesno")]
		public System.Nullable<bool> bng_HabitatPlanIncludedLegalAgreementYesNo
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_habitatplanincludedlegalagreementyesno");
			}
			set
			{
				this.SetAttributeValue("bng_habitatplanincludedlegalagreementyesno", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_inactivedate")]
		public System.Nullable<System.DateTime> bng_Inactivedate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_inactivedate");
			}
			set
			{
				this.SetAttributeValue("bng_inactivedate", value);
			}
		}
		
		/// <summary>
		/// This field is only for internal use. Not to be displayed.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_jsonforcasecreation")]
		public string bng_JSONForCaseCreation
		{
			get
			{
				return this.GetAttributeValue<string>("bng_jsonforcasecreation");
			}
			set
			{
				this.SetAttributeValue("bng_jsonforcasecreation", value);
			}
		}
		
		/// <summary>
		/// Land Boundary Document URL
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_landboundarydocumenturl")]
		public string bng_LandBoundaryDocumentURL
		{
			get
			{
				return this.GetAttributeValue<string>("bng_landboundarydocumenturl");
			}
			set
			{
				this.SetAttributeValue("bng_landboundarydocumenturl", value);
			}
		}
		
		/// <summary>
		/// The Land Boundary Grid Reference of the Biodiversity Gain Site.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_landboundarygridreference")]
		public string bng_LandBoundaryGridReference
		{
			get
			{
				return this.GetAttributeValue<string>("bng_landboundarygridreference");
			}
			set
			{
				this.SetAttributeValue("bng_landboundarygridreference", value);
			}
		}
		
		/// <summary>
		/// The Land Owner Consent Declaration flag related to the Biodiversity Gain Site Registration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_landownerconsentdeclaration")]
		public System.Nullable<bool> bng_LandOwnerConsentDeclaration
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_landownerconsentdeclaration");
			}
			set
			{
				this.SetAttributeValue("bng_landownerconsentdeclaration", value);
			}
		}
		
		/// <summary>
		/// Case Applicant, stored for use in Case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_landownerid")]
		public Microsoft.Xrm.Sdk.EntityReference bng_LandownerID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_landownerid");
			}
			set
			{
				this.SetAttributeValue("bng_landownerid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_legalagreementdatestatus")]
		public virtual bng_legalagreementdatestatus? bng_LegalAgreementDateStatus
		{
			get
			{
				return ((bng_legalagreementdatestatus?)(EntityOptionSetEnum.GetEnum(this, "bng_legalagreementdatestatus")));
			}
			set
			{
				this.SetAttributeValue("bng_legalagreementdatestatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// The End Date that relates to the Legal Agreement associated with the Biodiversity Gain Site.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_legalagreementenddate")]
		public System.Nullable<System.DateTime> bng_LegalAgreementEndDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_legalagreementenddate");
			}
			set
			{
				this.SetAttributeValue("bng_legalagreementenddate", value);
			}
		}
		
		/// <summary>
		/// The Length in Years of the Legal Agreement associated with the Biodiversity Gain Site.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_legalagreementlengthyears")]
		public System.Nullable<decimal> bng_LegalAgreementLengthYears
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bng_legalagreementlengthyears");
			}
		}
		
		/// <summary>
		/// The Start Date that relates to the Legal Agreement associated with the Biodiversity Gain Site.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_legalagreementstartdate")]
		public System.Nullable<System.DateTime> bng_LegalAgreementStartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_legalagreementstartdate");
			}
			set
			{
				this.SetAttributeValue("bng_legalagreementstartdate", value);
			}
		}
		
		/// <summary>
		/// The Legal Agreement Type that relates to the Biodiversity Gain Site.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_legalagreementtype")]
		public virtual bng_legalagreementtype? bng_LegalAgreementType
		{
			get
			{
				return ((bng_legalagreementtype?)(EntityOptionSetEnum.GetEnum(this, "bng_legalagreementtype")));
			}
			set
			{
				this.SetAttributeValue("bng_legalagreementtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// The Local Land Charges Register Reference associated with the Biodiversity Gain Site.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_locallandchargesregisterreference")]
		public string bng_LocalLandChargesRegisterReference
		{
			get
			{
				return this.GetAttributeValue<string>("bng_locallandchargesregisterreference");
			}
			set
			{
				this.SetAttributeValue("bng_locallandchargesregisterreference", value);
			}
		}
		
		/// <summary>
		/// Northing of a Land Boundary Grid Reference
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_northing")]
		public System.Nullable<int> bng_Northing
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bng_northing");
			}
			set
			{
				this.SetAttributeValue("bng_northing", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_organisationid")]
		public Microsoft.Xrm.Sdk.EntityReference bng_OrganisationID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_organisationid");
			}
			set
			{
				this.SetAttributeValue("bng_organisationid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_parentgainsite")]
		public Microsoft.Xrm.Sdk.EntityReference bng_ParentGainSite
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_parentgainsite");
			}
			set
			{
				this.SetAttributeValue("bng_parentgainsite", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_parentgainsiteref")]
		public string bng_ParentGainSiteRef
		{
			get
			{
				return this.GetAttributeValue<string>("bng_parentgainsiteref");
			}
			set
			{
				this.SetAttributeValue("bng_parentgainsiteref", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_paymentmethod")]
		public virtual bng_paymentmethodchoice? bng_PaymentMethod
		{
			get
			{
				return ((bng_paymentmethodchoice?)(EntityOptionSetEnum.GetEnum(this, "bng_paymentmethod")));
			}
			set
			{
				this.SetAttributeValue("bng_paymentmethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_paymentreference")]
		public string bng_PaymentReference
		{
			get
			{
				return this.GetAttributeValue<string>("bng_paymentreference");
			}
			set
			{
				this.SetAttributeValue("bng_paymentreference", value);
			}
		}
		
		/// <summary>
		/// Set by integration user when Gain Site Registration and related rows are created in PowerApps
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_readyforprocessingon")]
		public System.Nullable<System.DateTime> bng_ReadyForProcessingOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_readyforprocessingon");
			}
			set
			{
				this.SetAttributeValue("bng_readyforprocessingon", value);
			}
		}
		
		/// <summary>
		/// Allow an Operator to select a Rejection Reason when they Reject a Gain Site Registration Case
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_rejectionreasonid")]
		public Microsoft.Xrm.Sdk.EntityReference bng_RejectionReasonID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_rejectionreasonid");
			}
			set
			{
				this.SetAttributeValue("bng_rejectionreasonid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_responsiblebodycontact")]
		public Microsoft.Xrm.Sdk.EntityReference bng_ResponsibleBodyContact
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_responsiblebodycontact");
			}
			set
			{
				this.SetAttributeValue("bng_responsiblebodycontact", value);
			}
		}
		
		/// <summary>
		/// The Responsible for Enhancement Works Flag for the Applicant Related to the Biodiversity Gain Site Registration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_responsibleforenhancementworks")]
		public System.Nullable<bool> bng_ResponsibleforEnhancementWorks
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_responsibleforenhancementworks");
			}
			set
			{
				this.SetAttributeValue("bng_responsibleforenhancementworks", value);
			}
		}
		
		/// <summary>
		/// The Responsible for Managing Flag for the Applicant Related to the Biodiversity Gain Site Registration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_responsibleformanagingbiodiversitygainsite")]
		public System.Nullable<bool> bng_ResponsibleforManagingBiodiversityGainSite
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_responsibleformanagingbiodiversitygainsite");
			}
			set
			{
				this.SetAttributeValue("bng_responsibleformanagingbiodiversitygainsite", value);
			}
		}
		
		/// <summary>
		/// The Responsible for Monitoring Flag for the Applicant Related to the Biodiversity Gain Site Registration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_responsibleformonitoringbiodiversitygainsite")]
		public System.Nullable<bool> bng_ResponsibleforMonitoringBiodiversityGainSite
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_responsibleformonitoringbiodiversitygainsite");
			}
			set
			{
				this.SetAttributeValue("bng_responsibleformonitoringbiodiversitygainsite", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_source")]
		public virtual bng_source? bng_source
		{
			get
			{
				return ((bng_source?)(EntityOptionSetEnum.GetEnum(this, "bng_source")));
			}
			set
			{
				this.SetAttributeValue("bng_source", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// The Start Date that relates to the 30 Year Management & Monitoring Period associated with the Biodiversity Gain Site.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_yearmanagementmonitoringperiodstartdate")]
		public System.Nullable<System.DateTime> bng_YearManagementMonitoringPeriodStartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_yearmanagementmonitoringperiodstartdate");
			}
			set
			{
				this.SetAttributeValue("bng_yearmanagementmonitoringperiodstartdate", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created / submitted by the Portal.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Biodiversity Gain Site Registration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bng_gainsiteregistration_statecode? statecode
		{
			get
			{
				return ((bng_gainsiteregistration_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Biodiversity Gain Site Registration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bng_gainsiteregistration_statuscode? statuscode
		{
			get
			{
				return ((bng_gainsiteregistration_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N bng_biodiversityvalueunitchange_GainSiteID_bn
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_biodiversityvalueunitchange_GainSiteID_bn")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_BiodiversityValueUnitChange> bng_biodiversityvalueunitchange_GainSiteID_bn
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_BiodiversityValueUnitChange>("bng_biodiversityvalueunitchange_GainSiteID_bn", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_BiodiversityValueUnitChange>("bng_biodiversityvalueunitchange_GainSiteID_bn", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_bng_allocatedhabitats_GainSiteRegistratio
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_bng_allocatedhabitats_GainSiteRegistratio")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_AllocatedHabitats> bng_bng_allocatedhabitats_GainSiteRegistratio
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_AllocatedHabitats>("bng_bng_allocatedhabitats_GainSiteRegistratio", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_AllocatedHabitats>("bng_bng_allocatedhabitats_GainSiteRegistratio", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_bng_baselinehabitat_GainSiteID_bng_gainsi
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_bng_baselinehabitat_GainSiteID_bng_gainsi")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_BaselineHabitat> bng_bng_baselinehabitat_GainSiteID_bng_gainsi
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_BaselineHabitat>("bng_bng_baselinehabitat_GainSiteID_bng_gainsi", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_BaselineHabitat>("bng_bng_baselinehabitat_GainSiteID_bng_gainsi", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_bng_gainsitepropertylandowners_GainSiteRe
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_bng_gainsitepropertylandowners_GainSiteRe")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSitePropertyLandowners> bng_bng_gainsitepropertylandowners_GainSiteRe
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSitePropertyLandowners>("bng_bng_gainsitepropertylandowners_GainSiteRe", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSitePropertyLandowners>("bng_bng_gainsitepropertylandowners_GainSiteRe", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_Case_bng_GainSiteRegistrationID_bng_G
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_Case_bng_GainSiteRegistrationID_bng_G")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_Case> bng_Case_bng_GainSiteRegistrationID_bng_G
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Case>("bng_Case_bng_GainSiteRegistrationID_bng_G", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Case>("bng_Case_bng_GainSiteRegistrationID_bng_G", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_gainsiteregistration_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_gainsiteregistration_Annotations")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.Annotation> bng_gainsiteregistration_Annotations
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Annotation>("bng_gainsiteregistration_Annotations", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Annotation>("bng_gainsiteregistration_Annotations", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_gainsiteregistration_bng_Escalations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_gainsiteregistration_bng_Escalations")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_Escalation> bng_gainsiteregistration_bng_Escalations
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Escalation>("bng_gainsiteregistration_bng_Escalations", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Escalation>("bng_gainsiteregistration_bng_Escalations", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_gainsiteregistration_bng_Notifies
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_gainsiteregistration_bng_Notifies")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_Notify> bng_gainsiteregistration_bng_Notifies
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Notify>("bng_gainsiteregistration_bng_Notifies", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Notify>("bng_gainsiteregistration_bng_Notifies", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_GainSiteRegistration_EnforecementBodies
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_GainSiteRegistration_EnforecementBodies")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_EnforcementBody> bng_GainSiteRegistration_EnforecementBodies
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_EnforcementBody>("bng_GainSiteRegistration_EnforecementBodies", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_EnforcementBody>("bng_GainSiteRegistration_EnforecementBodies", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_gainsiteregistration_ParentGainSite_bng_g
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_gainsiteregistration_ParentGainSite_bng_g", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSiteRegistration> Referencedbng_gainsiteregistration_ParentGainSite_bng_g
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSiteRegistration>("bng_gainsiteregistration_ParentGainSite_bng_g", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSiteRegistration>("bng_gainsiteregistration_ParentGainSite_bng_g", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_HabitatType_bng_GainSiteRegistrationI
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_HabitatType_bng_GainSiteRegistrationI")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_HabitatType> bng_HabitatType_bng_GainSiteRegistrationI
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_HabitatType>("bng_HabitatType_bng_GainSiteRegistrationI", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_HabitatType>("bng_HabitatType_bng_GainSiteRegistrationI", null, value);
			}
		}
		
		/// <summary>
		/// 1:N bng_LegalAgreementParty_GainSiteRegistration
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_LegalAgreementParty_GainSiteRegistration")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_LegalAgreementParty> bng_LegalAgreementParty_GainSiteRegistration
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_LegalAgreementParty>("bng_LegalAgreementParty_GainSiteRegistration", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_LegalAgreementParty>("bng_LegalAgreementParty_GainSiteRegistration", null, value);
			}
		}
		
		/// <summary>
		/// N:N bng_DeveloperRegistration_GainSiteReg
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_DeveloperRegistration_GainSiteReg")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration> bng_DeveloperRegistration_GainSiteReg
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration>("bng_DeveloperRegistration_GainSiteReg", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration>("bng_DeveloperRegistration_GainSiteReg", null, value);
			}
		}
		
		/// <summary>
		/// N:N bng_GainSiteRegistration_Account_Account
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_GainSiteRegistration_Account_Account")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.Account> bng_GainSiteRegistration_Account_Account
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Account>("bng_GainSiteRegistration_Account_Account", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Account>("bng_GainSiteRegistration_Account_Account", null, value);
			}
		}
		
		/// <summary>
		/// N:N bng_GainSiteRegistration_bng_LocalPlanning
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_GainSiteRegistration_bng_LocalPlanning")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_LocalPlanningAuthority> bng_GainSiteRegistration_bng_LocalPlanning
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_LocalPlanningAuthority>("bng_GainSiteRegistration_bng_LocalPlanning", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_LocalPlanningAuthority>("bng_GainSiteRegistration_bng_LocalPlanning", null, value);
			}
		}
		
		/// <summary>
		/// N:N bng_GainSiteRegistration_Contact_Contact
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_GainSiteRegistration_Contact_Contact")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.Contact> bng_GainSiteRegistration_Contact_Contact
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_GainSiteRegistration_Contact_Contact", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_GainSiteRegistration_Contact_Contact", null, value);
			}
		}
		
		/// <summary>
		/// N:N bng_ResponsibleBody_bng_GainSiteRegistrat
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_ResponsibleBody_bng_GainSiteRegistrat")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_ResponsibleBody> bng_ResponsibleBody_bng_GainSiteRegistrat
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_ResponsibleBody>("bng_ResponsibleBody_bng_GainSiteRegistrat", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_ResponsibleBody>("bng_ResponsibleBody_bng_GainSiteRegistrat", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_bng_gainsiteregistration_LandownerID_cont
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_landownerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_bng_gainsiteregistration_LandownerID_cont")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Contact bng_bng_gainsiteregistration_LandownerID_cont
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_bng_gainsiteregistration_LandownerID_cont", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_bng_gainsiteregistration_LandownerID_cont", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_bng_gainsiteregistration_RejectionReasonI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_rejectionreasonid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_bng_gainsiteregistration_RejectionReasonI")]
		public DEFRA.NE.BNG.Integration.Domain.Models.bng_RejectionReason bng_bng_gainsiteregistration_RejectionReasonI
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_RejectionReason>("bng_bng_gainsiteregistration_RejectionReasonI", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_RejectionReason>("bng_bng_gainsiteregistration_RejectionReasonI", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_Contact_ApplicantContactID_bng_GainSiteRe
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_applicantcontactid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_Contact_ApplicantContactID_bng_GainSiteRe")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Contact bng_Contact_ApplicantContactID_bng_GainSiteRe
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_Contact_ApplicantContactID_bng_GainSiteRe", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_Contact_ApplicantContactID_bng_GainSiteRe", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_gainsiteregistration_EnforcementBodyConta
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_enforcementbodycontact")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_gainsiteregistration_EnforcementBodyConta")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Contact bng_gainsiteregistration_EnforcementBodyConta
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_gainsiteregistration_EnforcementBodyConta", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_gainsiteregistration_EnforcementBodyConta", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_GainSiteRegistration_OrganisationID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_organisationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_GainSiteRegistration_OrganisationID")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Account bng_GainSiteRegistration_OrganisationID
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Account>("bng_GainSiteRegistration_OrganisationID", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Account>("bng_GainSiteRegistration_OrganisationID", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_gainsiteregistration_ParentGainSite_bng_g
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_parentgainsite")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_gainsiteregistration_ParentGainSite_bng_g", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSiteRegistration Referencingbng_gainsiteregistration_ParentGainSite_bng_g
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSiteRegistration>("bng_gainsiteregistration_ParentGainSite_bng_g", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSiteRegistration>("bng_gainsiteregistration_ParentGainSite_bng_g", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_gainsiteregistration_ResponsibleBodyConta
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_responsiblebodycontact")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_gainsiteregistration_ResponsibleBodyConta")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Contact bng_gainsiteregistration_ResponsibleBodyConta
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_gainsiteregistration_ResponsibleBodyConta", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_gainsiteregistration_ResponsibleBodyConta", null, value);
			}
		}
		
		/// <summary>
		/// N:1 team_bng_gainsiteregistration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_bng_gainsiteregistration")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Team team_bng_gainsiteregistration
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Team>("team_bng_gainsiteregistration", null);
			}
		}
	}
}
#pragma warning restore CS1591
