#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	/// <summary>
	/// Status of the Biodiversity Value Unit Change
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_biodiversityvalueunitchange_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Biodiversity Value Unit Change
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum bng_biodiversityvalueunitchange_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bng_biodiversityvalueunitchange")]
	public partial class bng_BiodiversityValueUnitChange : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public bng_BiodiversityValueUnitChange() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bng_biodiversityvalueunitchange";
		
		public const string EntityLogicalCollectionName = "bng_biodiversityvalueunitchanges";
		
		public const string EntitySetName = "bng_biodiversityvalueunitchanges";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_area")]
		public System.Nullable<decimal> bng_Area
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bng_area");
			}
			set
			{
				this.SetAttributeValue("bng_area", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_biodiversityvalueunitchangeid")]
		public System.Nullable<System.Guid> bng_BiodiversityValueUnitChangeId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bng_biodiversityvalueunitchangeid");
			}
			set
			{
				this.SetAttributeValue("bng_biodiversityvalueunitchangeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_biodiversityvalueunitchangeid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.bng_BiodiversityValueUnitChangeId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_caseid")]
		public Microsoft.Xrm.Sdk.EntityReference bng_CaseID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_caseid");
			}
			set
			{
				this.SetAttributeValue("bng_caseid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_developmentid")]
		public Microsoft.Xrm.Sdk.EntityReference bng_DevelopmentID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_developmentid");
			}
			set
			{
				this.SetAttributeValue("bng_developmentid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_gainsiteid")]
		public Microsoft.Xrm.Sdk.EntityReference bng_GainSiteID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_gainsiteid");
			}
			set
			{
				this.SetAttributeValue("bng_gainsiteid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_hedgerow")]
		public System.Nullable<decimal> bng_Hedgerow
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bng_hedgerow");
			}
			set
			{
				this.SetAttributeValue("bng_hedgerow", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_name")]
		public string bng_Name
		{
			get
			{
				return this.GetAttributeValue<string>("bng_name");
			}
			set
			{
				this.SetAttributeValue("bng_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_watercourses")]
		public System.Nullable<decimal> bng_Watercourses
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bng_watercourses");
			}
			set
			{
				this.SetAttributeValue("bng_watercourses", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Biodiversity Value Unit Change
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual bng_biodiversityvalueunitchange_statecode? statecode
		{
			get
			{
				return ((bng_biodiversityvalueunitchange_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Reason for the status of the Biodiversity Value Unit Change
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual bng_biodiversityvalueunitchange_statuscode? statuscode
		{
			get
			{
				return ((bng_biodiversityvalueunitchange_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 bng_biodiversityvalueunitchange_CaseID_bng_ca
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_caseid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_biodiversityvalueunitchange_CaseID_bng_ca")]
		public DEFRA.NE.BNG.Integration.Domain.Models.bng_Case bng_biodiversityvalueunitchange_CaseID_bng_ca
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_Case>("bng_biodiversityvalueunitchange_CaseID_bng_ca", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_Case>("bng_biodiversityvalueunitchange_CaseID_bng_ca", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_biodiversityvalueunitchange_DevelopmentID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_developmentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_biodiversityvalueunitchange_DevelopmentID")]
		public DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration bng_biodiversityvalueunitchange_DevelopmentID
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration>("bng_biodiversityvalueunitchange_DevelopmentID", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration>("bng_biodiversityvalueunitchange_DevelopmentID", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_biodiversityvalueunitchange_GainSiteID_bn
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_gainsiteid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_biodiversityvalueunitchange_GainSiteID_bn")]
		public DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSiteRegistration bng_biodiversityvalueunitchange_GainSiteID_bn
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSiteRegistration>("bng_biodiversityvalueunitchange_GainSiteID_bn", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_GainSiteRegistration>("bng_biodiversityvalueunitchange_GainSiteID_bn", null, value);
			}
		}
		
		/// <summary>
		/// N:1 team_bng_biodiversityvalueunitchange
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_bng_biodiversityvalueunitchange")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Team team_bng_biodiversityvalueunitchange
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Team>("team_bng_biodiversityvalueunitchange", null);
			}
		}
	}
}
#pragma warning restore CS1591
