#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	/// <summary>
	/// Payment terms for the invoice.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invoice_paymenttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net30 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_210Net30 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net45 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net60 = 4,
	}
	
	/// <summary>
	/// Priority of the invoice.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invoice_prioritycode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for the invoice.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invoice_shippingmethodcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Airborne = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DHL = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FedEx = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UPS = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostalMail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FullLoad = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillCall = 7,
	}
	
	/// <summary>
	/// Freight terms for the shipping address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invoice_shipto_freighttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Status of the invoice.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invoice_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Paid = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 3,
	}
	
	/// <summary>
	/// Reason for the status of the invoice.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum invoice_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PartiallyShipped = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Billed = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Booked_appliestoservices = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Installed_appliestoservices = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RefundRequested = 759150001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled_deprecated = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PaidinFull_deprecated = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Complete = 100001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Partial = 100002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 100003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Paid = 759150002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Refunded = 355730001,
	}
	
	/// <summary>
	/// Order that has been billed
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("invoice")]
	public partial class Invoice : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Invoice() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "invoice";
		
		public const string EntityLogicalCollectionName = "invoices";
		
		public const string EntitySetName = "invoices";
		
		/// <summary>
		/// Unique identifier of the account with which the invoice is associated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountid")]
		public Microsoft.Xrm.Sdk.EntityReference AccountId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("accountid");
			}
		}
		
		/// <summary>
		/// Type the city for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_city")]
		public string BillTo_City
		{
			get
			{
				return this.GetAttributeValue<string>("billto_city");
			}
			set
			{
				this.SetAttributeValue("billto_city", value);
			}
		}
		
		/// <summary>
		/// Shows the complete Bill To address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_composite")]
		public string BillTo_Composite
		{
			get
			{
				return this.GetAttributeValue<string>("billto_composite");
			}
		}
		
		/// <summary>
		/// Type the country or region for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_country")]
		public string BillTo_Country
		{
			get
			{
				return this.GetAttributeValue<string>("billto_country");
			}
			set
			{
				this.SetAttributeValue("billto_country", value);
			}
		}
		
		/// <summary>
		/// Type the fax number for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_fax")]
		public string BillTo_Fax
		{
			get
			{
				return this.GetAttributeValue<string>("billto_fax");
			}
			set
			{
				this.SetAttributeValue("billto_fax", value);
			}
		}
		
		/// <summary>
		/// Type the first line of the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line1")]
		public string BillTo_Line1
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line1");
			}
			set
			{
				this.SetAttributeValue("billto_line1", value);
			}
		}
		
		/// <summary>
		/// Type the second line of the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line2")]
		public string BillTo_Line2
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line2");
			}
			set
			{
				this.SetAttributeValue("billto_line2", value);
			}
		}
		
		/// <summary>
		/// Type the third line of the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line3")]
		public string BillTo_Line3
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line3");
			}
			set
			{
				this.SetAttributeValue("billto_line3", value);
			}
		}
		
		/// <summary>
		/// Type a name for the customer's billing address, such as "Headquarters" or "Field office", to identify the address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_name")]
		public string BillTo_Name
		{
			get
			{
				return this.GetAttributeValue<string>("billto_name");
			}
			set
			{
				this.SetAttributeValue("billto_name", value);
			}
		}
		
		/// <summary>
		/// Type the ZIP Code or postal code for the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_postalcode")]
		public string BillTo_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("billto_postalcode");
			}
			set
			{
				this.SetAttributeValue("billto_postalcode", value);
			}
		}
		
		/// <summary>
		/// Type the state or province for the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_stateorprovince")]
		public string BillTo_StateOrProvince
		{
			get
			{
				return this.GetAttributeValue<string>("billto_stateorprovince");
			}
			set
			{
				this.SetAttributeValue("billto_stateorprovince", value);
			}
		}
		
		/// <summary>
		/// Type the phone number for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_telephone")]
		public string BillTo_Telephone
		{
			get
			{
				return this.GetAttributeValue<string>("billto_telephone");
			}
			set
			{
				this.SetAttributeValue("billto_telephone", value);
			}
		}
		
		/// <summary>
		/// Amount Paid For Invoice
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_amountpaid")]
		public Microsoft.Xrm.Sdk.Money bng_AmountPaid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("bng_amountpaid");
			}
			set
			{
				this.SetAttributeValue("bng_amountpaid", value);
			}
		}
		
		/// <summary>
		/// Value of the Amount Paid in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_amountpaid_base")]
		public Microsoft.Xrm.Sdk.Money bng_amountpaid_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("bng_amountpaid_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_amounttobepaid")]
		public Microsoft.Xrm.Sdk.Money bng_AmountToBePaid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("bng_amounttobepaid");
			}
		}
		
		/// <summary>
		/// Value of the Amount To Be Paid in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_amounttobepaid_base")]
		public Microsoft.Xrm.Sdk.Money bng_amounttobepaid_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("bng_amounttobepaid_base");
			}
		}
		
		/// <summary>
		/// Confirmation of Approval
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_confirmationofapproval")]
		public virtual bng_yesno? bng_ConfirmationofApproval
		{
			get
			{
				return ((bng_yesno?)(EntityOptionSetEnum.GetEnum(this, "bng_confirmationofapproval")));
			}
			set
			{
				this.SetAttributeValue("bng_confirmationofapproval", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_developmentid")]
		public Microsoft.Xrm.Sdk.EntityReference bng_DevelopmentID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_developmentid");
			}
			set
			{
				this.SetAttributeValue("bng_developmentid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_hascreditspaymentbeenreconciled")]
		public virtual bng_yesno? bng_hascreditspaymentbeenreconciled
		{
			get
			{
				return ((bng_yesno?)(EntityOptionSetEnum.GetEnum(this, "bng_hascreditspaymentbeenreconciled")));
			}
			set
			{
				this.SetAttributeValue("bng_hascreditspaymentbeenreconciled", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_hasproformainvoicebeenemailedtoapplicant")]
		public virtual bng_yesno? bng_hasproformaInvoicebeenemailedtoapplicant
		{
			get
			{
				return ((bng_yesno?)(EntityOptionSetEnum.GetEnum(this, "bng_hasproformainvoicebeenemailedtoapplicant")));
			}
			set
			{
				this.SetAttributeValue("bng_hasproformainvoicebeenemailedtoapplicant", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_hasproformainvoicebeengenerated")]
		public virtual bng_yesno? bng_hasproformaInvoicebeengenerated
		{
			get
			{
				return ((bng_yesno?)(EntityOptionSetEnum.GetEnum(this, "bng_hasproformainvoicebeengenerated")));
			}
			set
			{
				this.SetAttributeValue("bng_hasproformainvoicebeengenerated", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_hasproofofpurchasedocumentbeengenerated")]
		public virtual bng_yesno? bng_hasproofofpurchasedocumentbeengenerated
		{
			get
			{
				return ((bng_yesno?)(EntityOptionSetEnum.GetEnum(this, "bng_hasproofofpurchasedocumentbeengenerated")));
			}
			set
			{
				this.SetAttributeValue("bng_hasproofofpurchasedocumentbeengenerated", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_hasvatreceiptbeengenerated")]
		public virtual bng_yesno? bng_HasVATreceiptbeengenerated
		{
			get
			{
				return ((bng_yesno?)(EntityOptionSetEnum.GetEnum(this, "bng_hasvatreceiptbeengenerated")));
			}
			set
			{
				this.SetAttributeValue("bng_hasvatreceiptbeengenerated", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_invoicebillingaddress")]
		public string bng_InvoiceBillingAddress
		{
			get
			{
				return this.GetAttributeValue<string>("bng_invoicebillingaddress");
			}
			set
			{
				this.SetAttributeValue("bng_invoicebillingaddress", value);
			}
		}
		
		/// <summary>
		/// Column to be changed by pressing the "Notify Owner" button and thus trigger the "Create Notification for Owner of Invoice" cloud flow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_invoicechangenotification")]
		public System.Nullable<int> bng_InvoiceChangeNotification
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bng_invoicechangenotification");
			}
			set
			{
				this.SetAttributeValue("bng_invoicechangenotification", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_localplanningauthority")]
		public string bng_LocalPlanningAuthority
		{
			get
			{
				return this.GetAttributeValue<string>("bng_localplanningauthority");
			}
			set
			{
				this.SetAttributeValue("bng_localplanningauthority", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_partialamountpaid")]
		public Microsoft.Xrm.Sdk.Money bng_PartialAmountPaid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("bng_partialamountpaid");
			}
			set
			{
				this.SetAttributeValue("bng_partialamountpaid", value);
			}
		}
		
		/// <summary>
		/// Value of the Partial Amount Paid in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_partialamountpaid_base")]
		public Microsoft.Xrm.Sdk.Money bng_partialamountpaid_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("bng_partialamountpaid_base");
			}
		}
		
		/// <summary>
		/// Payment Date For The Invoice
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_paymentdate")]
		public System.Nullable<System.DateTime> bng_PaymentDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_paymentdate");
			}
			set
			{
				this.SetAttributeValue("bng_paymentdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_paymentdeadline")]
		public System.Nullable<System.DateTime> bng_PaymentDeadline
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_paymentdeadline");
			}
			set
			{
				this.SetAttributeValue("bng_paymentdeadline", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_planningauthority")]
		public string bng_PlanningAuthority
		{
			get
			{
				return this.GetAttributeValue<string>("bng_planningauthority");
			}
		}
		
		/// <summary>
		/// Purchase Order Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_ponumber")]
		public string bng_PONumber
		{
			get
			{
				return this.GetAttributeValue<string>("bng_ponumber");
			}
			set
			{
				this.SetAttributeValue("bng_ponumber", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_reconciliationstatus")]
		public virtual bng_reconciliationstatuschoices? bng_ReconciliationStatus
		{
			get
			{
				return ((bng_reconciliationstatuschoices?)(EntityOptionSetEnum.GetEnum(this, "bng_reconciliationstatus")));
			}
			set
			{
				this.SetAttributeValue("bng_reconciliationstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Refund Amount For Refund Request
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_refundamount")]
		public Microsoft.Xrm.Sdk.Money bng_RefundAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("bng_refundamount");
			}
			set
			{
				this.SetAttributeValue("bng_refundamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Refund Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_refundamount_base")]
		public Microsoft.Xrm.Sdk.Money bng_refundamount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("bng_refundamount_base");
			}
		}
		
		/// <summary>
		/// Refund Date For Refund Request
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_refunddate")]
		public System.Nullable<System.DateTime> bng_RefundDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bng_refunddate");
			}
			set
			{
				this.SetAttributeValue("bng_refunddate", value);
			}
		}
		
		/// <summary>
		/// ‘Refund Request For Invoice
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_refundrequested")]
		public System.Nullable<bool> bng_RefundRequested
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_refundrequested");
			}
			set
			{
				this.SetAttributeValue("bng_refundrequested", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_refundtype")]
		public virtual bng_refundtypeforinvoice? bng_RefundType
		{
			get
			{
				return ((bng_refundtypeforinvoice?)(EntityOptionSetEnum.GetEnum(this, "bng_refundtype")));
			}
			set
			{
				this.SetAttributeValue("bng_refundtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_transactionreference")]
		public string bng_TransactionReference
		{
			get
			{
				return this.GetAttributeValue<string>("bng_transactionreference");
			}
			set
			{
				this.SetAttributeValue("bng_transactionreference", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_vatreceiptandpurchaseproofsenttoapplicant")]
		public virtual bng_yesno? bng_VATReceiptandPurchaseProofsenttoapplicant
		{
			get
			{
				return ((bng_yesno?)(EntityOptionSetEnum.GetEnum(this, "bng_vatreceiptandpurchaseproofsenttoapplicant")));
			}
			set
			{
				this.SetAttributeValue("bng_vatreceiptandpurchaseproofsenttoapplicant", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the contact associated with the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactid")]
		public Microsoft.Xrm.Sdk.EntityReference ContactId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contactid");
			}
		}
		
		/// <summary>
		/// Shows who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Select the customer account or contact to provide a quick link to additional customer details, such as account information, activities, and opportunities.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		public Microsoft.Xrm.Sdk.EntityReference CustomerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("customerid");
			}
			set
			{
				this.SetAttributeValue("customerid", value);
			}
		}
		
		/// <summary>
		/// Enter the date when the products included in the invoice were delivered.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datedelivered")]
		public System.Nullable<System.DateTime> DateDelivered
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("datedelivered");
			}
			set
			{
				this.SetAttributeValue("datedelivered", value);
			}
		}
		
		/// <summary>
		/// Type additional information to describe the invoice, such as shipping details or product substitutions.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// Type the discount amount for the invoice if the customer is eligible for special savings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount")]
		public Microsoft.Xrm.Sdk.Money DiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount");
			}
			set
			{
				this.SetAttributeValue("discountamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Invoice Discount Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount_base")]
		public Microsoft.Xrm.Sdk.Money DiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount_base");
			}
		}
		
		/// <summary>
		/// Type the discount rate that should be applied to the Detail Amount field, for use in calculating the Pre-Freight Amount and Total Amount values for the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountpercentage")]
		public System.Nullable<decimal> DiscountPercentage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("discountpercentage");
			}
			set
			{
				this.SetAttributeValue("discountpercentage", value);
			}
		}
		
		/// <summary>
		/// Enter the date by which the invoice should be paid by the customer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duedate")]
		public System.Nullable<System.DateTime> DueDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("duedate");
			}
			set
			{
				this.SetAttributeValue("duedate", value);
			}
		}
		
		/// <summary>
		/// The primary email address for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
		public string EmailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("emailaddress");
			}
			set
			{
				this.SetAttributeValue("emailaddress", value);
			}
		}
		
		/// <summary>
		/// The default image for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
		public byte[] EntityImage
		{
			get
			{
				return this.GetAttributeValue<byte[]>("entityimage");
			}
			set
			{
				this.SetAttributeValue("entityimage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
		public System.Nullable<long> EntityImage_Timestamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
		public string EntityImage_URL
		{
			get
			{
				return this.GetAttributeValue<string>("entityimage_url");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
		public System.Nullable<System.Guid> EntityImageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
			}
		}
		
		/// <summary>
		/// Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Type the cost of freight or shipping for the products included in the invoice for use in calculating the total amount due.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount")]
		public Microsoft.Xrm.Sdk.Money FreightAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount");
			}
			set
			{
				this.SetAttributeValue("freightamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Freight Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount_base")]
		public Microsoft.Xrm.Sdk.Money FreightAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount_base");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("invoiceid")]
		public System.Nullable<System.Guid> InvoiceId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("invoiceid");
			}
			set
			{
				this.SetAttributeValue("invoiceid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("invoiceid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.InvoiceId = value;
			}
		}
		
		/// <summary>
		/// Shows the identifying number or code of the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("invoicenumber")]
		public string InvoiceNumber
		{
			get
			{
				return this.GetAttributeValue<string>("invoicenumber");
			}
			set
			{
				this.SetAttributeValue("invoicenumber", value);
			}
		}
		
		/// <summary>
		/// Select whether prices specified on the invoice are locked from any further updates.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ispricelocked")]
		public System.Nullable<bool> IsPriceLocked
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ispricelocked");
			}
			set
			{
				this.SetAttributeValue("ispricelocked", value);
			}
		}
		
		/// <summary>
		/// Enter the date and time when the invoice was last submitted to an accounting or ERP system for processing.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastbackofficesubmit")]
		public System.Nullable<System.DateTime> LastBackofficeSubmit
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastbackofficesubmit");
			}
			set
			{
				this.SetAttributeValue("lastbackofficesubmit", value);
			}
		}
		
		/// <summary>
		/// Contains the date time stamp of the last on hold time.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastonholdtime")]
		public System.Nullable<System.DateTime> LastOnHoldTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
			}
			set
			{
				this.SetAttributeValue("lastonholdtime", value);
			}
		}
		
		/// <summary>
		/// Shows who last updated the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Type a descriptive name for the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// Shows the duration in minutes for which the invoice was on hold.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("onholdtime")]
		public System.Nullable<int> OnHoldTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("onholdtime");
			}
		}
		
		/// <summary>
		/// Choose the opportunity that the invoice is related to for reporting and analytics.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opportunityid")]
		public Microsoft.Xrm.Sdk.EntityReference OpportunityId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opportunityid");
			}
			set
			{
				this.SetAttributeValue("opportunityid", value);
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Select the payment terms to indicate when the customer needs to pay the total amount.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("paymenttermscode")]
		public virtual invoice_paymenttermscode? PaymentTermsCode
		{
			get
			{
				return ((invoice_paymenttermscode?)(EntityOptionSetEnum.GetEnum(this, "paymenttermscode")));
			}
			set
			{
				this.SetAttributeValue("paymenttermscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Choose the price list associated with this record to make sure the products associated with the campaign are offered at the correct prices.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricelevelid")]
		public Microsoft.Xrm.Sdk.EntityReference PriceLevelId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pricelevelid");
			}
			set
			{
				this.SetAttributeValue("pricelevelid", value);
			}
		}
		
		/// <summary>
		/// Type of pricing error for the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingerrorcode")]
		public virtual qooi_pricingerrorcode? PricingErrorCode
		{
			get
			{
				return ((qooi_pricingerrorcode?)(EntityOptionSetEnum.GetEnum(this, "pricingerrorcode")));
			}
			set
			{
				this.SetAttributeValue("pricingerrorcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Select the priority so that preferred customers or critical issues are handled quickly.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("prioritycode")]
		public virtual invoice_prioritycode? PriorityCode
		{
			get
			{
				return ((invoice_prioritycode?)(EntityOptionSetEnum.GetEnum(this, "prioritycode")));
			}
			set
			{
				this.SetAttributeValue("prioritycode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.SetAttributeValue("processid", value);
			}
		}
		
		/// <summary>
		/// Choose the order related to the invoice to make sure the order is fulfilled and invoiced correctly.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderid")]
		public Microsoft.Xrm.Sdk.EntityReference SalesOrderId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("salesorderid");
			}
			set
			{
				this.SetAttributeValue("salesorderid", value);
			}
		}
		
		/// <summary>
		/// Select a shipping method for deliveries sent to this address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shippingmethodcode")]
		public virtual invoice_shippingmethodcode? ShippingMethodCode
		{
			get
			{
				return ((invoice_shippingmethodcode?)(EntityOptionSetEnum.GetEnum(this, "shippingmethodcode")));
			}
			set
			{
				this.SetAttributeValue("shippingmethodcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Type the city for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_city")]
		public string ShipTo_City
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_city");
			}
			set
			{
				this.SetAttributeValue("shipto_city", value);
			}
		}
		
		/// <summary>
		/// Shows the complete Ship To address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_composite")]
		public string ShipTo_Composite
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_composite");
			}
		}
		
		/// <summary>
		/// Type the country or region for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_country")]
		public string ShipTo_Country
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_country");
			}
			set
			{
				this.SetAttributeValue("shipto_country", value);
			}
		}
		
		/// <summary>
		/// Type the fax number for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_fax")]
		public string ShipTo_Fax
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_fax");
			}
			set
			{
				this.SetAttributeValue("shipto_fax", value);
			}
		}
		
		/// <summary>
		/// Select the freight terms to make sure shipping orders are processed correctly.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_freighttermscode")]
		public virtual invoice_shipto_freighttermscode? ShipTo_FreightTermsCode
		{
			get
			{
				return ((invoice_shipto_freighttermscode?)(EntityOptionSetEnum.GetEnum(this, "shipto_freighttermscode")));
			}
			set
			{
				this.SetAttributeValue("shipto_freighttermscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Type the first line of the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line1")]
		public string ShipTo_Line1
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line1");
			}
			set
			{
				this.SetAttributeValue("shipto_line1", value);
			}
		}
		
		/// <summary>
		/// Type the second line of the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line2")]
		public string ShipTo_Line2
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line2");
			}
			set
			{
				this.SetAttributeValue("shipto_line2", value);
			}
		}
		
		/// <summary>
		/// Type the third line of the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line3")]
		public string ShipTo_Line3
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line3");
			}
			set
			{
				this.SetAttributeValue("shipto_line3", value);
			}
		}
		
		/// <summary>
		/// Type a name for the customer's shipping address, such as "Headquarters" or "Field office",  to identify the address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_name")]
		public string ShipTo_Name
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_name");
			}
			set
			{
				this.SetAttributeValue("shipto_name", value);
			}
		}
		
		/// <summary>
		/// Type the ZIP Code or postal code for the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_postalcode")]
		public string ShipTo_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_postalcode");
			}
			set
			{
				this.SetAttributeValue("shipto_postalcode", value);
			}
		}
		
		/// <summary>
		/// Type the state or province for the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_stateorprovince")]
		public string ShipTo_StateOrProvince
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_stateorprovince");
			}
			set
			{
				this.SetAttributeValue("shipto_stateorprovince", value);
			}
		}
		
		/// <summary>
		/// Type the phone number for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_telephone")]
		public string ShipTo_Telephone
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_telephone");
			}
			set
			{
				this.SetAttributeValue("shipto_telephone", value);
			}
		}
		
		/// <summary>
		/// Skip Price Calculation (For Internal Use)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("skippricecalculation")]
		public virtual qooi_skippricecalculation? SkipPriceCalculation
		{
			get
			{
				return ((qooi_skippricecalculation?)(EntityOptionSetEnum.GetEnum(this, "skippricecalculation")));
			}
			set
			{
				this.SetAttributeValue("skippricecalculation", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Choose the service level agreement (SLA) that you want to apply to the invoice record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
		public Microsoft.Xrm.Sdk.EntityReference SLAId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slaid");
			}
			set
			{
				this.SetAttributeValue("slaid", value);
			}
		}
		
		/// <summary>
		/// Last SLA that was applied to this invoice. This field is for internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedid")]
		public Microsoft.Xrm.Sdk.EntityReference SLAInvokedId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slainvokedid");
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.SetAttributeValue("stageid", value);
			}
		}
		
		/// <summary>
		/// Shows whether the invoice is active, paid, or canceled. Paid and canceled invoices are read-only and can't be edited unless they are reactivated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual invoice_statecode? StateCode
		{
			get
			{
				return ((invoice_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Select the invoice's status.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual invoice_statuscode? StatusCode
		{
			get
			{
				return ((invoice_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Shows the total amount due, calculated as the sum of the products, discount, freight, and taxes for the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount")]
		public Microsoft.Xrm.Sdk.Money TotalAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount");
			}
			set
			{
				this.SetAttributeValue("totalamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount_base");
			}
		}
		
		/// <summary>
		/// Shows the total product amount due, minus any discounts. This value is added to freight and tax amounts in the calculation for the total amount due for the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight")]
		public Microsoft.Xrm.Sdk.Money TotalAmountLessFreight
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight");
			}
			set
			{
				this.SetAttributeValue("totalamountlessfreight", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Pre-Freight Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight_base")]
		public Microsoft.Xrm.Sdk.Money TotalAmountLessFreight_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight_base");
			}
		}
		
		/// <summary>
		/// Shows the total discount amount, based on the discount price and rate entered on the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount")]
		public Microsoft.Xrm.Sdk.Money TotalDiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount");
			}
			set
			{
				this.SetAttributeValue("totaldiscountamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Discount Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalDiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount_base");
			}
		}
		
		/// <summary>
		/// Shows the sum of all existing and write-in products included on the invoice, based on the specified price list and quantities.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount");
			}
			set
			{
				this.SetAttributeValue("totallineitemamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Detail Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount_base");
			}
		}
		
		/// <summary>
		/// Shows the Manual Discount amounts specified on all products included in the invoice. This value is reflected in the Detail Amount field on the invoice and is added to any discount amount or rate specified on the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount");
			}
			set
			{
				this.SetAttributeValue("totallineitemdiscountamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Line Item Discount Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount_base");
			}
		}
		
		/// <summary>
		/// Shows the total of the Tax amounts specified on all products included in the invoice, included in the Total Amount due calculation for the invoice.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax")]
		public Microsoft.Xrm.Sdk.Money TotalTax
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax");
			}
			set
			{
				this.SetAttributeValue("totaltax", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Tax in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax_base")]
		public Microsoft.Xrm.Sdk.Money TotalTax_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax_base");
			}
		}
		
		/// <summary>
		/// Choose the local currency for the record to make sure budgets are reported in the correct currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.SetAttributeValue("traversedpath", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Select whether the products included in the invoice should be shipped to the specified address or held until the customer calls with further pick up or delivery instructions.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("willcall")]
		public System.Nullable<bool> WillCall
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("willcall");
			}
			set
			{
				this.SetAttributeValue("willcall", value);
			}
		}
		
		/// <summary>
		/// 1:N Invoice_Annotation
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Invoice_Annotation")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.Annotation> Invoice_Annotation
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Annotation>("Invoice_Annotation", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Annotation>("Invoice_Annotation", null, value);
			}
		}
		
		/// <summary>
		/// 1:N invoice_bng_Escalations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("invoice_bng_Escalations")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_Escalation> invoice_bng_Escalations
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Escalation>("invoice_bng_Escalations", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Escalation>("invoice_bng_Escalations", null, value);
			}
		}
		
		/// <summary>
		/// 1:N invoice_bng_Notifies
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("invoice_bng_Notifies")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_Notify> invoice_bng_Notifies
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Notify>("invoice_bng_Notifies", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Notify>("invoice_bng_Notifies", null, value);
			}
		}
		
		/// <summary>
		/// N:N contactinvoices_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contactinvoices_association")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.Contact> contactinvoices_association
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("contactinvoices_association", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("contactinvoices_association", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_invoice_DevelopmentID_bng_developerregist
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_developmentid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_invoice_DevelopmentID_bng_developerregist")]
		public DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration bng_invoice_DevelopmentID_bng_developerregist
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration>("bng_invoice_DevelopmentID_bng_developerregist", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration>("bng_invoice_DevelopmentID_bng_developerregist", null, value);
			}
		}
		
		/// <summary>
		/// N:1 invoice_customer_accounts
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("invoice_customer_accounts")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Account invoice_customer_accounts
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Account>("invoice_customer_accounts", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Account>("invoice_customer_accounts", null, value);
			}
		}
		
		/// <summary>
		/// N:1 invoice_customer_contacts
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("invoice_customer_contacts")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Contact invoice_customer_contacts
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("invoice_customer_contacts", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("invoice_customer_contacts", null, value);
			}
		}
		
		/// <summary>
		/// N:1 order_invoices
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("order_invoices")]
		public DEFRA.NE.BNG.Integration.Domain.Models.SalesOrder order_invoices
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.SalesOrder>("order_invoices", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.SalesOrder>("order_invoices", null, value);
			}
		}
		
		/// <summary>
		/// N:1 team_invoices
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_invoices")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Team team_invoices
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Team>("team_invoices", null);
			}
		}
	}
}
#pragma warning restore CS1591
