#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEFRA.NE.BNG.Integration.Domain.Models
{
	
	
	/// <summary>
	/// Freight terms for the order.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum salesorder_freighttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FOB = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoCharge = 2,
	}
	
	/// <summary>
	/// Payment terms for the order.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum salesorder_paymenttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net30 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		_210Net30 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net45 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Net60 = 4,
	}
	
	/// <summary>
	/// Priority of the order.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum salesorder_prioritycode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Method of shipment for the order.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum salesorder_shippingmethodcode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Airborne = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DHL = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FedEx = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UPS = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PostalMail = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FullLoad = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WillCall = 7,
	}
	
	/// <summary>
	/// Freight terms for the shipping address.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum salesorder_shipto_freighttermscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultValue = 1,
	}
	
	/// <summary>
	/// Status of the order.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum salesorder_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Submitted = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fulfilled = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invoiced = 4,
	}
	
	/// <summary>
	/// Reason for the status of the order.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum salesorder_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoPayment = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Withdrawn = 759150002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RefusaltoDischarge = 759150003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CDDChecksFailed = 759150004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pending = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Complete = 100001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Partial = 100002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invoiced = 100003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OnHold = 759150001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NoresponsetoRFI = 759150005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Planningpermissionalreadycommenced = 759150006,
	}
	
	/// <summary>
	/// Quote that has been accepted.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("salesorder")]
	public partial class SalesOrder : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public SalesOrder() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "salesorder";
		
		public const string EntityLogicalCollectionName = "salesorders";
		
		public const string EntitySetName = "salesorders";
		
		/// <summary>
		/// Shows the parent account related to the record. This information is used to link the sales order to the account selected in the Customer field for reporting and analytics.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountid")]
		public Microsoft.Xrm.Sdk.EntityReference AccountId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("accountid");
			}
		}
		
		/// <summary>
		/// Unique identifier of the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_addressid")]
		public System.Nullable<System.Guid> BillTo_AddressId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("billto_addressid");
			}
			set
			{
				this.SetAttributeValue("billto_addressid", value);
			}
		}
		
		/// <summary>
		/// Type the city for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_city")]
		public string BillTo_City
		{
			get
			{
				return this.GetAttributeValue<string>("billto_city");
			}
			set
			{
				this.SetAttributeValue("billto_city", value);
			}
		}
		
		/// <summary>
		/// Shows the complete Bill To address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_composite")]
		public string BillTo_Composite
		{
			get
			{
				return this.GetAttributeValue<string>("billto_composite");
			}
		}
		
		/// <summary>
		/// Type the primary contact name at the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_contactname")]
		public string BillTo_ContactName
		{
			get
			{
				return this.GetAttributeValue<string>("billto_contactname");
			}
			set
			{
				this.SetAttributeValue("billto_contactname", value);
			}
		}
		
		/// <summary>
		/// Type the country or region for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_country")]
		public string BillTo_Country
		{
			get
			{
				return this.GetAttributeValue<string>("billto_country");
			}
			set
			{
				this.SetAttributeValue("billto_country", value);
			}
		}
		
		/// <summary>
		/// Type the fax number for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_fax")]
		public string BillTo_Fax
		{
			get
			{
				return this.GetAttributeValue<string>("billto_fax");
			}
			set
			{
				this.SetAttributeValue("billto_fax", value);
			}
		}
		
		/// <summary>
		/// Type the first line of the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line1")]
		public string BillTo_Line1
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line1");
			}
			set
			{
				this.SetAttributeValue("billto_line1", value);
			}
		}
		
		/// <summary>
		/// Type the second line of the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line2")]
		public string BillTo_Line2
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line2");
			}
			set
			{
				this.SetAttributeValue("billto_line2", value);
			}
		}
		
		/// <summary>
		/// Type the third line of the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_line3")]
		public string BillTo_Line3
		{
			get
			{
				return this.GetAttributeValue<string>("billto_line3");
			}
			set
			{
				this.SetAttributeValue("billto_line3", value);
			}
		}
		
		/// <summary>
		/// Type a name for the customer's billing address, such as "Headquarters" or "Field office", to identify the address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_name")]
		public string BillTo_Name
		{
			get
			{
				return this.GetAttributeValue<string>("billto_name");
			}
			set
			{
				this.SetAttributeValue("billto_name", value);
			}
		}
		
		/// <summary>
		/// Type the ZIP Code or postal code for the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_postalcode")]
		public string BillTo_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("billto_postalcode");
			}
			set
			{
				this.SetAttributeValue("billto_postalcode", value);
			}
		}
		
		/// <summary>
		/// Type the state or province for the billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_stateorprovince")]
		public string BillTo_StateOrProvince
		{
			get
			{
				return this.GetAttributeValue<string>("billto_stateorprovince");
			}
			set
			{
				this.SetAttributeValue("billto_stateorprovince", value);
			}
		}
		
		/// <summary>
		/// Type the phone number for the customer's billing address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billto_telephone")]
		public string BillTo_Telephone
		{
			get
			{
				return this.GetAttributeValue<string>("billto_telephone");
			}
			set
			{
				this.SetAttributeValue("billto_telephone", value);
			}
		}
		
		/// <summary>
		/// Email Content for Order Cancellation Email Template
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_contentforordercancellationemailtemplate")]
		public string bng_ContentforOrderCancellationEmailTemplate
		{
			get
			{
				return this.GetAttributeValue<string>("bng_contentforordercancellationemailtemplate");
			}
			set
			{
				this.SetAttributeValue("bng_contentforordercancellationemailtemplate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_customercontactid")]
		public Microsoft.Xrm.Sdk.EntityReference bng_CustomerContactID
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_customercontactid");
			}
			set
			{
				this.SetAttributeValue("bng_customercontactid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_developerregistration")]
		public Microsoft.Xrm.Sdk.EntityReference bng_DeveloperRegistration
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_developerregistration");
			}
			set
			{
				this.SetAttributeValue("bng_developerregistration", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_hasapplicantamlcheckspassed")]
		public virtual bng_yesnona? bng_HasapplicantAMLcheckspassed
		{
			get
			{
				return ((bng_yesnona?)(EntityOptionSetEnum.GetEnum(this, "bng_hasapplicantamlcheckspassed")));
			}
			set
			{
				this.SetAttributeValue("bng_hasapplicantamlcheckspassed", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_hasapplicantpassedamlchecks")]
		public virtual bng_yesno? bng_HasapplicantpassedAMLchecks
		{
			get
			{
				return ((bng_yesno?)(EntityOptionSetEnum.GetEnum(this, "bng_hasapplicantpassedamlchecks")));
			}
			set
			{
				this.SetAttributeValue("bng_hasapplicantpassedamlchecks", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_hasthedevelopmentreceivedplanningpermission")]
		public virtual bng_yesno? bng_Hasthedevelopmentreceivedplanningpermission
		{
			get
			{
				return ((bng_yesno?)(EntityOptionSetEnum.GetEnum(this, "bng_hasthedevelopmentreceivedplanningpermission")));
			}
			set
			{
				this.SetAttributeValue("bng_hasthedevelopmentreceivedplanningpermission", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_lpacontact")]
		public Microsoft.Xrm.Sdk.EntityReference bng_LPAContact
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bng_lpacontact");
			}
			set
			{
				this.SetAttributeValue("bng_lpacontact", value);
			}
		}
		
		/// <summary>
		/// Column to be changed by pressing the "Notify Owner" button and thus trigger the "Create Notification for Owner of Order" cloud flow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_orderchangenotification")]
		public System.Nullable<int> bng_OrderChangeNotification
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bng_orderchangenotification");
			}
			set
			{
				this.SetAttributeValue("bng_orderchangenotification", value);
			}
		}
		
		/// <summary>
		/// Column to be changed by pressing the "Notify Owner" button and thus trigger the "Create Notification for Owner of Order" cloud flow
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_orderchangenotificationsubgrid")]
		public System.Nullable<int> bng_OrderChangeNotificationSubgrid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("bng_orderchangenotificationsubgrid");
			}
			set
			{
				this.SetAttributeValue("bng_orderchangenotificationsubgrid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_orderstatus")]
		public virtual bng_orderproposedstatus? bng_OrderStatus
		{
			get
			{
				return ((bng_orderproposedstatus?)(EntityOptionSetEnum.GetEnum(this, "bng_orderstatus")));
			}
			set
			{
				this.SetAttributeValue("bng_orderstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_paymentreceived")]
		public System.Nullable<bool> bng_PaymentReceived
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_paymentreceived");
			}
			set
			{
				this.SetAttributeValue("bng_paymentreceived", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_ponumber")]
		public string bng_ponumber
		{
			get
			{
				return this.GetAttributeValue<string>("bng_ponumber");
			}
			set
			{
				this.SetAttributeValue("bng_ponumber", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_proposedstatus")]
		public virtual bng_reviewstatus? bng_ProposedStatus
		{
			get
			{
				return ((bng_reviewstatus?)(EntityOptionSetEnum.GetEnum(this, "bng_proposedstatus")));
			}
			set
			{
				this.SetAttributeValue("bng_proposedstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Refund Requested For Credit Orders
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_refundrequested")]
		public System.Nullable<bool> bng_RefundRequested
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("bng_refundrequested");
			}
			set
			{
				this.SetAttributeValue("bng_refundrequested", value);
			}
		}
		
		/// <summary>
		/// Source
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_source")]
		public virtual bng_source? bng_Source
		{
			get
			{
				return ((bng_source?)(EntityOptionSetEnum.GetEnum(this, "bng_source")));
			}
			set
			{
				this.SetAttributeValue("bng_source", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Shows the campaign that the order was created from.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("campaignid")]
		public Microsoft.Xrm.Sdk.EntityReference CampaignId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("campaignid");
			}
			set
			{
				this.SetAttributeValue("campaignid", value);
			}
		}
		
		/// <summary>
		/// Shows the parent contact related to the record. This information is used to link the contract to the contact selected in the Customer field for reporting and analytics.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactid")]
		public Microsoft.Xrm.Sdk.EntityReference ContactId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contactid");
			}
		}
		
		/// <summary>
		/// Shows who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Select the customer account or contact to provide a quick link to additional customer details, such as account information, activities, and opportunities.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		public Microsoft.Xrm.Sdk.EntityReference CustomerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("customerid");
			}
			set
			{
				this.SetAttributeValue("customerid", value);
			}
		}
		
		/// <summary>
		/// Enter the date that all or part of the order was shipped to the customer.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datefulfilled")]
		public System.Nullable<System.DateTime> DateFulfilled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("datefulfilled");
			}
			set
			{
				this.SetAttributeValue("datefulfilled", value);
			}
		}
		
		/// <summary>
		/// Type additional information to describe the order, such as the products or services offered or details about the customer's product preferences.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// Type the discount amount for the order if the customer is eligible for special savings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount")]
		public Microsoft.Xrm.Sdk.Money DiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount");
			}
			set
			{
				this.SetAttributeValue("discountamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Order Discount Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountamount_base")]
		public Microsoft.Xrm.Sdk.Money DiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("discountamount_base");
			}
		}
		
		/// <summary>
		/// Type the discount rate that should be applied to the Detail Amount field to include additional savings for the customer in the order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("discountpercentage")]
		public System.Nullable<decimal> DiscountPercentage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("discountpercentage");
			}
			set
			{
				this.SetAttributeValue("discountpercentage", value);
			}
		}
		
		/// <summary>
		/// The primary email address for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
		public string EmailAddress
		{
			get
			{
				return this.GetAttributeValue<string>("emailaddress");
			}
			set
			{
				this.SetAttributeValue("emailaddress", value);
			}
		}
		
		/// <summary>
		/// The default image for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
		public byte[] EntityImage
		{
			get
			{
				return this.GetAttributeValue<byte[]>("entityimage");
			}
			set
			{
				this.SetAttributeValue("entityimage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
		public System.Nullable<long> EntityImage_Timestamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
		public string EntityImage_URL
		{
			get
			{
				return this.GetAttributeValue<string>("entityimage_url");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
		public System.Nullable<System.Guid> EntityImageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
			}
		}
		
		/// <summary>
		/// Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Type the cost of freight or shipping for the products included in the order for use in calculating the Total Amount field.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount")]
		public Microsoft.Xrm.Sdk.Money FreightAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount");
			}
			set
			{
				this.SetAttributeValue("freightamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Freight Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freightamount_base")]
		public Microsoft.Xrm.Sdk.Money FreightAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("freightamount_base");
			}
		}
		
		/// <summary>
		/// Select the freight terms to make sure shipping charges are processed correctly.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("freighttermscode")]
		public virtual salesorder_freighttermscode? FreightTermsCode
		{
			get
			{
				return ((salesorder_freighttermscode?)(EntityOptionSetEnum.GetEnum(this, "freighttermscode")));
			}
			set
			{
				this.SetAttributeValue("freighttermscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Select whether prices specified on the invoice are locked from any further updates.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ispricelocked")]
		public System.Nullable<bool> IsPriceLocked
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ispricelocked");
			}
			set
			{
				this.SetAttributeValue("ispricelocked", value);
			}
		}
		
		/// <summary>
		/// Enter the date and time when the order was last submitted to an accounting or ERP system for processing.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastbackofficesubmit")]
		public System.Nullable<System.DateTime> LastBackofficeSubmit
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastbackofficesubmit");
			}
			set
			{
				this.SetAttributeValue("lastbackofficesubmit", value);
			}
		}
		
		/// <summary>
		/// Contains the date time stamp of the last on hold time.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastonholdtime")]
		public System.Nullable<System.DateTime> LastOnHoldTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
			}
			set
			{
				this.SetAttributeValue("lastonholdtime", value);
			}
		}
		
		/// <summary>
		/// Shows who last updated the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Type a descriptive name for the order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// Shows the duration in minutes for which the order was on hold.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("onholdtime")]
		public System.Nullable<int> OnHoldTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("onholdtime");
			}
		}
		
		/// <summary>
		/// Choose the related opportunity so that the data for the order and opportunity are linked for reporting and analytics.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("opportunityid")]
		public Microsoft.Xrm.Sdk.EntityReference OpportunityId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("opportunityid");
			}
			set
			{
				this.SetAttributeValue("opportunityid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ordercreationmethod")]
		public virtual salesordercreationmethod? OrderCreationMethod
		{
			get
			{
				return ((salesordercreationmethod?)(EntityOptionSetEnum.GetEnum(this, "ordercreationmethod")));
			}
			set
			{
				this.SetAttributeValue("ordercreationmethod", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Shows the order number for customer reference and to use in search. The number cannot be modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ordernumber")]
		public string OrderNumber
		{
			get
			{
				return this.GetAttributeValue<string>("ordernumber");
			}
			set
			{
				this.SetAttributeValue("ordernumber", value);
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id Renamed To Assigned To
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Select the payment terms to indicate when the customer needs to pay the total amount.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("paymenttermscode")]
		public virtual salesorder_paymenttermscode? PaymentTermsCode
		{
			get
			{
				return ((salesorder_paymenttermscode?)(EntityOptionSetEnum.GetEnum(this, "paymenttermscode")));
			}
			set
			{
				this.SetAttributeValue("paymenttermscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Choose the price list associated with this record to make sure the products associated with the campaign are offered at the correct prices.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricelevelid")]
		public Microsoft.Xrm.Sdk.EntityReference PriceLevelId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pricelevelid");
			}
			set
			{
				this.SetAttributeValue("pricelevelid", value);
			}
		}
		
		/// <summary>
		/// Select the type of pricing error, such as a missing or invalid product, or missing quantity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingerrorcode")]
		public virtual qooi_pricingerrorcode? PricingErrorCode
		{
			get
			{
				return ((qooi_pricingerrorcode?)(EntityOptionSetEnum.GetEnum(this, "pricingerrorcode")));
			}
			set
			{
				this.SetAttributeValue("pricingerrorcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Select the priority so that preferred customers or critical issues are handled quickly.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("prioritycode")]
		public virtual salesorder_prioritycode? PriorityCode
		{
			get
			{
				return ((salesorder_prioritycode?)(EntityOptionSetEnum.GetEnum(this, "prioritycode")));
			}
			set
			{
				this.SetAttributeValue("prioritycode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.SetAttributeValue("processid", value);
			}
		}
		
		/// <summary>
		/// Choose the related quote so that order data and quote data are linked for reporting and analytics.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quoteid")]
		public Microsoft.Xrm.Sdk.EntityReference QuoteId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("quoteid");
			}
			set
			{
				this.SetAttributeValue("quoteid", value);
			}
		}
		
		/// <summary>
		/// Enter the delivery date requested by the customer for all products in the order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requestdeliveryby")]
		public System.Nullable<System.DateTime> RequestDeliveryBy
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("requestdeliveryby");
			}
			set
			{
				this.SetAttributeValue("requestdeliveryby", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderid")]
		public System.Nullable<System.Guid> SalesOrderId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("salesorderid");
			}
			set
			{
				this.SetAttributeValue("salesorderid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.SalesOrderId = value;
			}
		}
		
		/// <summary>
		/// Select a shipping method for deliveries sent to this address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shippingmethodcode")]
		public virtual salesorder_shippingmethodcode? ShippingMethodCode
		{
			get
			{
				return ((salesorder_shippingmethodcode?)(EntityOptionSetEnum.GetEnum(this, "shippingmethodcode")));
			}
			set
			{
				this.SetAttributeValue("shippingmethodcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Unique identifier of the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_addressid")]
		public System.Nullable<System.Guid> ShipTo_AddressId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("shipto_addressid");
			}
			set
			{
				this.SetAttributeValue("shipto_addressid", value);
			}
		}
		
		/// <summary>
		/// Type the city for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_city")]
		public string ShipTo_City
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_city");
			}
			set
			{
				this.SetAttributeValue("shipto_city", value);
			}
		}
		
		/// <summary>
		/// Shows the complete Ship To address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_composite")]
		public string ShipTo_Composite
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_composite");
			}
		}
		
		/// <summary>
		/// Type the primary contact name at the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_contactname")]
		public string ShipTo_ContactName
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_contactname");
			}
			set
			{
				this.SetAttributeValue("shipto_contactname", value);
			}
		}
		
		/// <summary>
		/// Type the country or region for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_country")]
		public string ShipTo_Country
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_country");
			}
			set
			{
				this.SetAttributeValue("shipto_country", value);
			}
		}
		
		/// <summary>
		/// Type the fax number for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_fax")]
		public string ShipTo_Fax
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_fax");
			}
			set
			{
				this.SetAttributeValue("shipto_fax", value);
			}
		}
		
		/// <summary>
		/// Select the freight terms to make sure shipping orders are processed correctly.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_freighttermscode")]
		public virtual salesorder_shipto_freighttermscode? ShipTo_FreightTermsCode
		{
			get
			{
				return ((salesorder_shipto_freighttermscode?)(EntityOptionSetEnum.GetEnum(this, "shipto_freighttermscode")));
			}
			set
			{
				this.SetAttributeValue("shipto_freighttermscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Type the first line of the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line1")]
		public string ShipTo_Line1
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line1");
			}
			set
			{
				this.SetAttributeValue("shipto_line1", value);
			}
		}
		
		/// <summary>
		/// Type the second line of the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line2")]
		public string ShipTo_Line2
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line2");
			}
			set
			{
				this.SetAttributeValue("shipto_line2", value);
			}
		}
		
		/// <summary>
		/// Type the third line of the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line3")]
		public string ShipTo_Line3
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_line3");
			}
			set
			{
				this.SetAttributeValue("shipto_line3", value);
			}
		}
		
		/// <summary>
		/// Type a name for the customer's shipping address, such as "Headquarters" or "Field office",  to identify the address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_name")]
		public string ShipTo_Name
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_name");
			}
			set
			{
				this.SetAttributeValue("shipto_name", value);
			}
		}
		
		/// <summary>
		/// Type the ZIP Code or postal code for the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_postalcode")]
		public string ShipTo_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_postalcode");
			}
			set
			{
				this.SetAttributeValue("shipto_postalcode", value);
			}
		}
		
		/// <summary>
		/// Type the state or province for the shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_stateorprovince")]
		public string ShipTo_StateOrProvince
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_stateorprovince");
			}
			set
			{
				this.SetAttributeValue("shipto_stateorprovince", value);
			}
		}
		
		/// <summary>
		/// Type the phone number for the customer's shipping address.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_telephone")]
		public string ShipTo_Telephone
		{
			get
			{
				return this.GetAttributeValue<string>("shipto_telephone");
			}
			set
			{
				this.SetAttributeValue("shipto_telephone", value);
			}
		}
		
		/// <summary>
		/// Skip Price Calculation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("skippricecalculation")]
		public virtual qooi_skippricecalculation? SkipPriceCalculation
		{
			get
			{
				return ((qooi_skippricecalculation?)(EntityOptionSetEnum.GetEnum(this, "skippricecalculation")));
			}
			set
			{
				this.SetAttributeValue("skippricecalculation", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Choose the service level agreement (SLA) that you want to apply to the sales order record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
		public Microsoft.Xrm.Sdk.EntityReference SLAId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slaid");
			}
			set
			{
				this.SetAttributeValue("slaid", value);
			}
		}
		
		/// <summary>
		/// Last SLA that was applied to this sales order. This field is for internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedid")]
		public Microsoft.Xrm.Sdk.EntityReference SLAInvokedId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slainvokedid");
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.SetAttributeValue("stageid", value);
			}
		}
		
		/// <summary>
		/// Shows whether the order is active, submitted, fulfilled, canceled, or invoiced. Only active orders can be edited.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual salesorder_statecode? StateCode
		{
			get
			{
				return ((salesorder_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Select the order's status.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual salesorder_statuscode? StatusCode
		{
			get
			{
				return ((salesorder_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		/// <summary>
		/// Enter the date when the order was submitted to the fulfillment or shipping center.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("submitdate")]
		public System.Nullable<System.DateTime> SubmitDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("submitdate");
			}
			set
			{
				this.SetAttributeValue("submitdate", value);
			}
		}
		
		/// <summary>
		/// Type the code for the submitted status in the fulfillment or shipping center system.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("submitstatus")]
		public System.Nullable<int> SubmitStatus
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("submitstatus");
			}
			set
			{
				this.SetAttributeValue("submitstatus", value);
			}
		}
		
		/// <summary>
		/// Type additional details or notes about the order for the fulfillment or shipping center.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("submitstatusdescription")]
		public string SubmitStatusDescription
		{
			get
			{
				return this.GetAttributeValue<string>("submitstatusdescription");
			}
			set
			{
				this.SetAttributeValue("submitstatusdescription", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Shows the total amount due, calculated as the sum of the products, discounts, freight, and taxes for the order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount")]
		public Microsoft.Xrm.Sdk.Money TotalAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount");
			}
			set
			{
				this.SetAttributeValue("totalamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamount_base");
			}
		}
		
		/// <summary>
		/// Shows the total product amount for the order, minus any discounts. This value is added to freight and tax amounts in the calculation for the total amount due for the order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight")]
		public Microsoft.Xrm.Sdk.Money TotalAmountLessFreight
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight");
			}
			set
			{
				this.SetAttributeValue("totalamountlessfreight", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Pre-Freight Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalamountlessfreight_base")]
		public Microsoft.Xrm.Sdk.Money TotalAmountLessFreight_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totalamountlessfreight_base");
			}
		}
		
		/// <summary>
		/// Shows the total discount amount, based on the discount price and rate entered on the order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount")]
		public Microsoft.Xrm.Sdk.Money TotalDiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount");
			}
			set
			{
				this.SetAttributeValue("totaldiscountamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Discount Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaldiscountamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalDiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaldiscountamount_base");
			}
		}
		
		/// <summary>
		/// Shows the sum of all existing and write-in products included on the order, based on the specified price list and quantities.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount");
			}
			set
			{
				this.SetAttributeValue("totallineitemamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Detail Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemamount_base");
			}
		}
		
		/// <summary>
		/// Shows the total of the Manual Discount amounts specified on all products included in the order. This value is reflected in the Detail Amount field on the order and is added to any discount amount or rate specified on the order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount");
			}
			set
			{
				this.SetAttributeValue("totallineitemdiscountamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Line Item Discount Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totallineitemdiscountamount_base")]
		public Microsoft.Xrm.Sdk.Money TotalLineItemDiscountAmount_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totallineitemdiscountamount_base");
			}
		}
		
		/// <summary>
		/// Shows the Tax amounts specified on all products included in the order, included in the Total Amount due calculation for the order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax")]
		public Microsoft.Xrm.Sdk.Money TotalTax
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax");
			}
			set
			{
				this.SetAttributeValue("totaltax", value);
			}
		}
		
		/// <summary>
		/// Value of the Total Tax in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totaltax_base")]
		public Microsoft.Xrm.Sdk.Money TotalTax_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("totaltax_base");
			}
		}
		
		/// <summary>
		/// Choose the local currency for the record to make sure budgets are reported in the correct currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.SetAttributeValue("traversedpath", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Select whether the products included in the order should be shipped to the specified address or held until the customer calls with further pick-up or delivery instructions.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("willcall")]
		public System.Nullable<bool> WillCall
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("willcall");
			}
			set
			{
				this.SetAttributeValue("willcall", value);
			}
		}
		
		/// <summary>
		/// 1:N bng_CustomerDueDiligenceCheck_OrderID_Sal
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_CustomerDueDiligenceCheck_OrderID_Sal")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_CustomerDueDiligenceCheck> bng_CustomerDueDiligenceCheck_OrderID_Sal
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_CustomerDueDiligenceCheck>("bng_CustomerDueDiligenceCheck_OrderID_Sal", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_CustomerDueDiligenceCheck>("bng_CustomerDueDiligenceCheck_OrderID_Sal", null, value);
			}
		}
		
		/// <summary>
		/// 1:N order_details
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("order_details")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.SalesOrderDetail> order_details
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.SalesOrderDetail>("order_details", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.SalesOrderDetail>("order_details", null, value);
			}
		}
		
		/// <summary>
		/// 1:N order_invoices
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("order_invoices")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.Invoice> order_invoices
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Invoice>("order_invoices", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Invoice>("order_invoices", null, value);
			}
		}
		
		/// <summary>
		/// 1:N SalesOrder_Annotation
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrder_Annotation")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.Annotation> SalesOrder_Annotation
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Annotation>("SalesOrder_Annotation", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Annotation>("SalesOrder_Annotation", null, value);
			}
		}
		
		/// <summary>
		/// 1:N salesorder_bng_Escalations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorder_bng_Escalations")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_Escalation> salesorder_bng_Escalations
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Escalation>("salesorder_bng_Escalations", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Escalation>("salesorder_bng_Escalations", null, value);
			}
		}
		
		/// <summary>
		/// 1:N salesorder_bng_Notifies
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorder_bng_Notifies")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.bng_Notify> salesorder_bng_Notifies
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Notify>("salesorder_bng_Notifies", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.bng_Notify>("salesorder_bng_Notifies", null, value);
			}
		}
		
		/// <summary>
		/// N:N contactorders_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contactorders_association")]
		public System.Collections.Generic.IEnumerable<DEFRA.NE.BNG.Integration.Domain.Models.Contact> contactorders_association
		{
			get
			{
				return this.GetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("contactorders_association", null);
			}
			set
			{
				this.SetRelatedEntities<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("contactorders_association", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_DeveloperRegistration_bng_Order
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_developerregistration")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_DeveloperRegistration_bng_Order")]
		public DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration bng_DeveloperRegistration_bng_Order
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration>("bng_DeveloperRegistration_bng_Order", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.bng_DeveloperRegistration>("bng_DeveloperRegistration_bng_Order", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_salesorder_CustomerContactID_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_customercontactid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_salesorder_CustomerContactID_contact")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Contact bng_salesorder_CustomerContactID_contact
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_salesorder_CustomerContactID_contact", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_salesorder_CustomerContactID_contact", null, value);
			}
		}
		
		/// <summary>
		/// N:1 bng_salesorder_LPAContact_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bng_lpacontact")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bng_salesorder_LPAContact_contact")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Contact bng_salesorder_LPAContact_contact
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_salesorder_LPAContact_contact", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("bng_salesorder_LPAContact_contact", null, value);
			}
		}
		
		/// <summary>
		/// N:1 order_customer_accounts
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("order_customer_accounts")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Account order_customer_accounts
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Account>("order_customer_accounts", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Account>("order_customer_accounts", null, value);
			}
		}
		
		/// <summary>
		/// N:1 order_customer_contacts
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("order_customer_contacts")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Contact order_customer_contacts
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("order_customer_contacts", null);
			}
			set
			{
				this.SetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Contact>("order_customer_contacts", null, value);
			}
		}
		
		/// <summary>
		/// N:1 team_orders
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_orders")]
		public DEFRA.NE.BNG.Integration.Domain.Models.Team team_orders
		{
			get
			{
				return this.GetRelatedEntity<DEFRA.NE.BNG.Integration.Domain.Models.Team>("team_orders", null);
			}
		}
	}
}
#pragma warning restore CS1591
